FROM python:alpine3.7

LABEL maintainer="Eakkapat Pattarathamrong (overbid@gmail.com)"

RUN pip install --upgrade pip setuptools \
    && pip install --upgrade httpie httpie-jwt-auth pyopenssl ndg-httpsclient pyasn1
